-- schema.sql
CREATE TABLE IF NOT EXISTS Broths (
Id INT PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(25) NOT NULL,
IsVegan BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS Noodles (
Id INT PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(25) NOT NULL,
BrothId INT NOT NULL,
CONSTRAINT FK_Noodles_Broths_BrothId FOREIGN KEY (BrothId) REFERENCES Broths (Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Garnishes (
Id INT PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(25) NOT NULL,
NoodleId INT,
CONSTRAINT FK_Garnishes_Noodles_NoodleId FOREIGN KEY (NoodleId) REFERENCES Noodles (Id)
);